// Default Lightroom develop-settings Lua string - verbatim port of the
// template in src/catalog/writer.py. All editing sliders are zeroed; per-image
// camera profile fields are preserved by passing them in.

export function buildDefaultSettings(
  cameraProfile: string,
  cameraProfileDigest: string,
): string {
  const cp = cameraProfile.replace(/"/g, '\\"');
  const cpd = cameraProfileDigest.replace(/"/g, '\\"');
  return `s = { AutoLateralCA = 0,
Blacks2012 = 0,
Brightness = 50,
CameraProfile = "${cp}",
CameraProfileDigest = "${cpd}",
ColorGradeBlending = 50,
ColorGradeGlobalHue = 0,
ColorGradeGlobalLum = 0,
ColorGradeGlobalSat = 0,
ColorGradeHighlightLum = 0,
ColorGradeMidtoneHue = 0,
ColorGradeMidtoneLum = 0,
ColorGradeMidtoneSat = 0,
ColorGradeShadowLum = 0,
ColorNoiseReduction = 25,
Contrast = 25,
Contrast2012 = 0,
ConvertToGrayscale = false,
CurveRefineSaturation = 100,
DefringeGreenAmount = 0,
DefringeGreenHueHi = 60,
DefringeGreenHueLo = 40,
DefringePurpleAmount = 0,
DefringePurpleHueHi = 70,
DefringePurpleHueLo = 30,
EnableDistractionRemoval = true,
Exposure = 0,
Exposure2012 = 0,
FilterList = {  },
GrainSize = 25,
HDREditMode = 0,
HDRMaxValue = 2.3,
Highlights2012 = 0,
LensBlur = {  },
LensManualDistortionAmount = 0,
LensProfileEnable = 0,
LensProfileSetup = "LensDefaults",
Look = { Amount = 1,
Copyright = "© 2018 Adobe Systems, Inc.",
Group = { ["x-default"] = "Profiles" },
Name = "Adobe Color",
Parameters = { CameraProfile = "Adobe Standard",
ConvertToGrayscale = false,
FilterList = {  },
LookTable = "E1095149FDB39D7A057BAB208837E2E1",
PointColors = {  },
ProcessVersion = "15.4",
ToneCurveName2012 = "",
ToneCurvePV2012 = { 0,
0,
22,
16,
40,
35,
127,
127,
224,
230,
240,
246,
255,
255 },
ToneCurvePV2012Blue = { 0,
0,
255,
255 },
ToneCurvePV2012Green = { 0,
0,
255,
255 },
ToneCurvePV2012Red = { 0,
0,
255,
255 },
Version = "18.2" },
SupportsAmount = false,
SupportsMonochrome = false,
SupportsOutputReferred = false,
UUID = "B952C231111CD8E0ECCF14B86BAA7077" },
LuminanceNoiseReductionContrast = 0,
OverrideLookVignette = false,
PerspectiveHorizontal = 0,
PerspectiveRotate = 0,
PerspectiveScale = 100,
PerspectiveVertical = 0,
PerspectiveX = 0,
PerspectiveY = 0,
PointColors = {  },
ProcessVersion = "15.4",
RedEyeInfo = {  },
SDRBlend = 0,
SDRBrightness = 0,
SDRClarity = 0,
SDRContrast = 0,
SDRHighlights = 0,
SDRShadows = 0,
SDRWhites = 0,
Saturation = 0,
Shadows = 5,
Shadows2012 = 0,
SharpenDetail = 25,
SharpenEdgeMasking = 0,
SharpenRadius = 1,
Sharpness = 40,
Temperature = 5500,
Tint = 0,
ToneCurveName2012 = "Linear",
ToneCurvePV2012 = { 0,
0,
255,
255 },
ToneCurvePV2012Blue = { 0,
0,
255,
255 },
ToneCurvePV2012Green = { 0,
0,
255,
255 },
ToneCurvePV2012Red = { 0,
0,
255,
255 },
UprightCenterMode = 0,
UprightCenterNormX = 0.5,
UprightCenterNormY = 0.5,
UprightFocalLength35mm = 35,
UprightFocalMode = 0,
UprightFourSegmentsCount = 0,
UprightPreview = false,
UprightTransformCount = 6,
UprightVersion = 151388160,
Version = "18.2",
Vibrance = 0,
WhiteBalance = "As Shot",
Whites2012 = 0 }`;
}

// Extract CameraProfile and CameraProfileDigest from the top-level of a
// settings text. We need the *first* occurrence at line start to avoid matching
// the nested ones inside Look.Parameters.
export function extractCameraInfo(text: string): {
  cameraProfile: string;
  cameraProfileDigest: string;
} {
  let cameraProfile = 'Adobe Standard';
  let cameraProfileDigest = '';
  const m1 = text.match(/^CameraProfile = "([^"]+)"/m);
  if (m1) cameraProfile = m1[1];
  const m2 = text.match(/^CameraProfileDigest = "([^"]+)"/m);
  if (m2) cameraProfileDigest = m2[1];
  return { cameraProfile, cameraProfileDigest };
}
